version: "3"
services:
  pgadmin:
    image: dpage/pgadmin4:4.25
    ports:
      - "5050:80"
    env_file:
     - ./.env.local
    depends_on:
      - db
  db:
    image: postgres
    ports: 
      - "5432:5432"
    restart: always
    env_file:
      - ./.env.local