/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomina.gui.panels;

import nomina.entities.Empleado;

/**
 *
 * @author RickyTB
 */
public class EmployeeDetailPanel extends javax.swing.JPanel {
    private final Empleado empleado;

    /**
     * Creates new form EmployeeDetailPanel
     * @param empleado
     */
    public EmployeeDetailPanel(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        fillData();
    }
    
    private void fillData() {
        nameLabel.setText(empleado.getNombre() + " " + empleado.getApellido());
        cedulaLabel.setText(empleado.getCedula());
        emailLabel.setText(empleado.getEmail());
        direccionLabel.setText(empleado.getDireccion());
        numeroCuentaLabel.setText(empleado.getNumeroCuenta());
        sexoLabel.setText(empleado.getSexo());
        estadoCivilLabel.setText(empleado.getEstadoCivil());
        telefonoLabel.setText("" +empleado.getTelefono());
        nacionalidadLabel.setText(empleado.getNacionalidad());
        cargoLabel.setText(empleado.getCargoId().getNombre());
        departamentoLabel.setText(empleado.getDepartamentoId().getNombre());
        tipoContratoLabel.setText(empleado.getTipoContratoId().getNombre());
        fechaIngresoLabel.setText(empleado.getFechaIngreso().toString());
        fechaSalidaLabel.setText(empleado.getFechaSalida() != null ? empleado.getFechaSalida().toString() : "N/A");
        sueldoLabel.setText("$" + empleado.getSueldo().toPlainString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedulaLabelLabel = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        estadoCivilLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        telefonoLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        cedulaLabel = new javax.swing.JLabel();
        emailLabel1 = new javax.swing.JLabel();
        direccionLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        cedulaLabelLabel1 = new javax.swing.JLabel();
        emailLabel2 = new javax.swing.JLabel();
        direccionLabel2 = new javax.swing.JLabel();
        direccionLabel3 = new javax.swing.JLabel();
        numeroCuentaLabel = new javax.swing.JLabel();
        direccionLabel5 = new javax.swing.JLabel();
        nacionalidadLabel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        cedulaLabelLabel2 = new javax.swing.JLabel();
        cargoLabel = new javax.swing.JLabel();
        cedulaLabelLabel3 = new javax.swing.JLabel();
        departamentoLabel = new javax.swing.JLabel();
        tipoContratoLabel = new javax.swing.JLabel();
        cedulaLabelLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        fechaIngresoLabel = new javax.swing.JLabel();
        cedulaLabelLabel5 = new javax.swing.JLabel();
        fechaSalidaLabel = new javax.swing.JLabel();
        cedulaLabelLabel6 = new javax.swing.JLabel();
        cedulaLabelLabel7 = new javax.swing.JLabel();
        sueldoLabel = new javax.swing.JLabel();

        cedulaLabelLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel.setText("Cédula");

        direccionLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        direccionLabel.setText("Dirección:");

        emailLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailLabel.setText("Email:");

        estadoCivilLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        estadoCivilLabel.setText("Estado Civil:");

        sexoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sexoLabel.setText("Sexo:");

        telefonoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telefonoLabel.setText("Teléfono:");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nameLabel.setText("Nombre Apellido");

        cedulaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cedulaLabel.setText("Cédula");

        emailLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        emailLabel1.setText("Email");

        direccionLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        direccionLabel1.setText("Dirección");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        cedulaLabelLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel1.setText("Sexo");

        emailLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        emailLabel2.setText("Estado Civil");

        direccionLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        direccionLabel2.setText("Teléfono");

        direccionLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        direccionLabel3.setText("Número de cuenta");

        numeroCuentaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        numeroCuentaLabel.setText("Dirección:");

        direccionLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        direccionLabel5.setText("Nacionalidad");

        nacionalidadLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        nacionalidadLabel.setText("Dirección:");

        cedulaLabelLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel2.setText("Cargo");

        cargoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cargoLabel.setText("Cargo");

        cedulaLabelLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel3.setText("Departamento");

        departamentoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        departamentoLabel.setText("Departamento");

        tipoContratoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tipoContratoLabel.setText("Tipo de contrato");

        cedulaLabelLabel4.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel4.setText("Tipo de contrato");

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        fechaIngresoLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaIngresoLabel.setText("01/01/2020");

        cedulaLabelLabel5.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel5.setText("Fecha ingreso");

        fechaSalidaLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fechaSalidaLabel.setText("01/01/2020");

        cedulaLabelLabel6.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel6.setText("Fecha salida");

        cedulaLabelLabel7.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        cedulaLabelLabel7.setText("Sueldo");

        sueldoLabel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        sueldoLabel.setText("$4500.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cedulaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroCuentaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cedulaLabelLabel)
                                    .addComponent(emailLabel1)
                                    .addComponent(direccionLabel1)
                                    .addComponent(direccionLabel3))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sexoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(estadoCivilLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telefonoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nacionalidadLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(direccionLabel2)
                                    .addComponent(cedulaLabelLabel1)
                                    .addComponent(emailLabel2)
                                    .addComponent(direccionLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(departamentoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cedulaLabelLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedulaLabelLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cedulaLabelLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cargoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tipoContratoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaIngresoLabel)
                            .addComponent(cedulaLabelLabel5)
                            .addComponent(fechaSalidaLabel)
                            .addComponent(cedulaLabelLabel6))
                        .addGap(353, 353, 353))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cedulaLabelLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sueldoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cedulaLabelLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sexoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(estadoCivilLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(telefonoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(direccionLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nacionalidadLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(cedulaLabelLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedulaLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(direccionLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(numeroCuentaLabel))
                    .addComponent(jSeparator1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(cedulaLabelLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cargoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cedulaLabelLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(departamentoLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cedulaLabelLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tipoContratoLabel))
                        .addComponent(jSeparator3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cedulaLabelLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaIngresoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cedulaLabelLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaSalidaLabel)))
                .addGap(18, 18, 18)
                .addComponent(cedulaLabelLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sueldoLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cargoLabel;
    private javax.swing.JLabel cedulaLabel;
    private javax.swing.JLabel cedulaLabelLabel;
    private javax.swing.JLabel cedulaLabelLabel1;
    private javax.swing.JLabel cedulaLabelLabel2;
    private javax.swing.JLabel cedulaLabelLabel3;
    private javax.swing.JLabel cedulaLabelLabel4;
    private javax.swing.JLabel cedulaLabelLabel5;
    private javax.swing.JLabel cedulaLabelLabel6;
    private javax.swing.JLabel cedulaLabelLabel7;
    private javax.swing.JLabel departamentoLabel;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JLabel direccionLabel1;
    private javax.swing.JLabel direccionLabel2;
    private javax.swing.JLabel direccionLabel3;
    private javax.swing.JLabel direccionLabel5;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailLabel1;
    private javax.swing.JLabel emailLabel2;
    private javax.swing.JLabel estadoCivilLabel;
    private javax.swing.JLabel fechaIngresoLabel;
    private javax.swing.JLabel fechaSalidaLabel;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel nacionalidadLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel numeroCuentaLabel;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JLabel sueldoLabel;
    private javax.swing.JLabel telefonoLabel;
    private javax.swing.JLabel tipoContratoLabel;
    // End of variables declaration//GEN-END:variables
}
