/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomina.gui;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import nomina.entities.Concepto;
import nomina.interfaces.ChooseConceptListener;
import nomina.interfaces.SimpleDocumentListener;

/**
 *
 * @author RickyTB
 */
public class AddLendConcept extends javax.swing.JFrame {

    private static final DecimalFormat DF2 = new DecimalFormat("#.##");

    private double lendValue = 0.0;
    private double rateValue = 0.0;
    private int monthsValue = 0;
    private final ChooseConceptListener listener;

    /**
     * Creates new form AddLendConcept
     * @param listener
     */
    public AddLendConcept(ChooseConceptListener listener) {
        this.listener = listener;
        initComponents();
        prepareUI();
    }

    private void prepareUI() {
        updateTotal();

        lendValueField.getDocument().addDocumentListener((SimpleDocumentListener) e -> {
            try {
                lendValue = Double.parseDouble((String) lendValueField.getText());
            } catch (NumberFormatException ex) {
                lendValue = 0;
            }
            updateTotal();
        });
        rateField.getDocument().addDocumentListener((SimpleDocumentListener) e -> {
            try {
                rateValue = Double.parseDouble((String) rateField.getText());
            } catch (NumberFormatException ex) {
                rateValue = 0;
            }
            updateTotal();
        });
        monthsField.getDocument().addDocumentListener((SimpleDocumentListener) e -> {
            try {
                monthsValue = Integer.parseInt((String) monthsField.getText());
            } catch (NumberFormatException ex) {
                monthsValue = 0;
            }
            updateTotal();
        });
    }
    
    private double calculateTotal() {
        if (monthsValue == 0) return 0;
        return (lendValue + (lendValue * rateValue)) / (double) monthsValue;
    }

    private void updateTotal() {
        totalLabel.setText("$" + DF2.format(calculateTotal()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lendValueField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        rateField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        monthsField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        totalLabel = new javax.swing.JLabel();
        acceptButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar préstamo");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Agregar préstamo");

        jLabel2.setText("Valor total préstamo");

        jLabel3.setText("Tasa de interés (0.xx)");

        jLabel4.setText("Meses de duración");

        jLabel5.setText("Valor a descontar");

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalLabel.setText("$0.00");

        acceptButton.setText("Aceptar");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lendValueField)
                    .addComponent(rateField)
                    .addComponent(monthsField)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(totalLabel)
                            .addComponent(acceptButton))
                        .addGap(0, 459, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lendValueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(monthsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLabel)
                .addGap(18, 18, 18)
                .addComponent(acceptButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        Concepto concepto = new Concepto();
        concepto.setNombre("Préstamo");
        concepto.setTipo(Concepto.EGRESO);
        concepto.setValor(BigDecimal.valueOf(calculateTotal()));
        listener.onAddConcept(concepto);
        dispose();
    }//GEN-LAST:event_acceptButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField lendValueField;
    private javax.swing.JTextField monthsField;
    private javax.swing.JTextField rateField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
