/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nomina.gui;

import nomina.entities.Empleado;
import nomina.gui.panels.EmployeeDetailPanel;
import nomina.gui.panels.FamilyPanel;
import nomina.gui.panels.PaymentsPanel;

/**
 *
 * @author RickyTB
 */
public class EmployeeDetailFrame extends javax.swing.JFrame {

    private final Empleado empleado;

    /**
     * Creates new form EmployeeDetailFrame
     *
     * @param empleado
     */
    public EmployeeDetailFrame(Empleado empleado) {
        this.empleado = empleado;
        initComponents();
        setupFrame();
    }

    private void setupFrame() {
        setTitle("Empleado: " + empleado.getNombre() + " " + empleado.getApellido());
        tabbedPane.addTab("Detalles", new EmployeeDetailPanel(empleado));
        tabbedPane.addTab("Cargas familiares", new FamilyPanel(empleado));
        tabbedPane.addTab("Roles de pago", new PaymentsPanel(empleado));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabbedPane.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tabbedPane;
    // End of variables declaration//GEN-END:variables
}
